<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <PropertyGroup>
    <IsPackable>true</IsPackable>
    <GeneratePackageOnBuild>True</GeneratePackageOnBuild>
    <Version>0.0.1</Version>
    <Description>Minimalistic async wrapper around Topstep API.</Description>
    <Authors>artemiusgreat</Authors>
    <Copyright>indemos.com</Copyright>
    <PackageProjectUrl>http://indemos.com</PackageProjectUrl>
    <RepositoryUrl>https://github.com/artemiusgreat/TopstepX</RepositoryUrl>
    <PackageTags>TopstepX</PackageTags>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Http.Connections" Version="1.2.11" />
    <PackageReference Include="Microsoft.AspNetCore.Http.Connections.Common" Version="10.0.10" />
    <PackageReference Include="Microsoft.AspNetCore.SignalR.Client" Version="10.0.10" />
  </ItemGroup>

</Project>
